trial = {
   "_id":"621fa7e8ac211300176be205",
   "model_name":"TemplateRecipe",
   "recipe_name":"FFA_Test_Recipe_V1",
   "recipe_variable":"Light and Temperature",
   "phases":[
      {
         "name":"growth",
         "phase_start":0,
         "step":[
            {
               "circulation_fan":[
                  {
                     "start_time":[
                        0,
                        0
                     ],
                     "setting":1
                  }
               ]
            },
            {
               "temperature":[
                  {
                     "start_time":[
                        0,
                        0
                     ],
                     "setting":95
                  }
               ]
            },
	    {
               "pump_amount":[
                  {
                     "start_time":[
                        11,
                        7
                     ],
                     "setting":20
                  },
		  {
                     "start_time":[
                        12,
                        8
                     ],
                     "setting":30
                  },
		  {
                     "start_time":[
                        16,
                        40
                     ],
                     "setting":150
                  },
		  {
                     "start_time":[
                        16,
                        45
                     ],
                     "setting":150
                  },
		  {
                     "start_time":[
                        16,
                        50
                     ],
                     "setting":150
                  },
		  {
                     "start_time":[
                        16,
                        55
                     ],
                     "setting":150
                  },
		  {
                     "start_time":[
                        17,
                        0
                     ],
                     "setting":150
                  },
		  {
                     "start_time":[
                        17,
                        5
                     ],
                     "setting":150
                  },
		  {
                     "start_time":[
                        17,
                        10
                     ],
                     "setting":150
                  },
		  {
                     "start_time":[
                        17,
                        15
                     ],
                     "setting":150
                  },
		  {
                     "start_time":[
                        17,
                        20
                     ],
                     "setting":150
                  },
		  {
                     "start_time":[
                        17,
                        25
                     ],
                     "setting":150
                  },
		  {
                     "start_time":[
                        17,
                        30
                     ],
                     "setting":150
                  },
		  {
                     "start_time":[
                        17,
                        35
                     ],
                     "setting":150
                  },
		  {
                     "start_time":[
                        17,
                        37
                     ],
                     "setting":150
                  },
		  {
                     "start_time":[
                        17,
                        42
                     ],
                     "setting":150
                  },
		  {
                     "start_time":[
                        17,
                        45
                     ],
                     "setting":150
                  },
		  {
                     "start_time":[
                        17,
                        50
                     ],
                     "setting":150
                  },
		  {
                     "start_time":[
                        17,
                        52
                     ],
                     "setting":150
                  },
		  {
                     "start_time":[
                        17,
                        55
                     ],
                     "setting":150
                  },
		  {
                     "start_time":[
                        17,
                        57
                     ],
                     "setting":150
                  }
               ]
            },
            {
               "light_intensity":[
                  {
                     "start_time":[
                        0,
                        0
                     ],
                     "setting":[
                        0,
                        0,
                        0,
                        0
                     ]
                  },
                  {
                     "start_time":[
                        9,
                        0
                     ],
                     "setting":[
                        255,
                        255,
                        255,
                        255
                     ]
                  },
                  {
                     "start_time":[
                        16,
                        40
                     ],
                     "setting":[
                        255,
                        0,
                        0,
                        0
                     ]
                  },
                  {
                     "start_time":[
                        16,
                        41
                     ],
                     "setting":[
                        0,
                        255,
                        0,
                        0
                     ]
                  },
                  {
                     "start_time":[
                        16,
                        42
                     ],
                     "setting":[
                        255,
                        255,
                        0,
                        0
                     ]
                  },
                  {
                     "start_time":[
                        16,
                        43
                     ],
                     "setting":[
                        255,
                        255,
                        255,
                        0
                     ]
                  },
                  {
                     "start_time":[
                        16,
                        44
                     ],
                     "setting":[
                        0,
                        255,
                        255,
                        255
                     ]
                  },
                  {
                     "start_time":[
                        16,
                        45
                     ],
                     "setting":[
                        0,
                        0,
                        255,
                        255
                     ]
                  },
                  {
                     "start_time":[
                        16,
                        46
                     ],
                     "setting":[
                        0,
                        0,
                        0,
                        255
                     ]
                  },
                  {
                     "start_time":[
                        16,
                        47
                     ],
                     "setting":[
                        50,
                        120,
                        150,
                        200
                     ]
                  },
                  {
                     "start_time":[
                        16,
                        48
                     ],
                     "setting":[
                        0,
                        150,
                        150,
                        0
                     ]
                  },
                  {
                     "start_time":[
                        16,
                        49
                     ],
                     "setting":[
                        0,
                        0,
                        0,
                        0
                     ]
                  },
                  {
                     "start_time":[
                        16,
                        50
                     ],
                     "setting":[
                        255,
                        0,
                        0,
                        0
                     ]
                  },
                  {
                     "start_time":[
                        16,
                        51
                     ],
                     "setting":[
                        0,
                        255,
                        0,
                        0
                     ]
                  },
                  {
                     "start_time":[
                        16,
                        52
                     ],
                     "setting":[
                        255,
                        255,
                        0,
                        0
                     ]
                  },
                  {
                     "start_time":[
                        16,
                        53
                     ],
                     "setting":[
                        255,
                        255,
                        255,
                        0
                     ]
                  },
                  {
                     "start_time":[
                        16,
                        54
                     ],
                     "setting":[
                        0,
                        255,
                        255,
                        255
                     ]
                  },
                  {
                     "start_time":[
                        16,
                        55
                     ],
                     "setting":[
                        0,
                        0,
                        255,
                        255
                     ]
                  },
                  {
                     "start_time":[
                        16,
                        56
                     ],
                     "setting":[
                        0,
                        0,
                        0,
                        255
                     ]
                  },
                  {
                     "start_time":[
                        16,
                        57
                     ],
                     "setting":[
                        50,
                        120,
                        150,
                        200
                     ]
                  },
                  {
                     "start_time":[
                        16,
                        58
                     ],
                     "setting":[
                        0,
                        150,
                        150,
                        0
                     ]
                  },
                  {
                     "start_time":[
                        16,
                        59
                     ],
                     "setting":[
                        0,
                        0,
                        0,
                        0
                     ]
                  },                  
                  {
                     "start_time":[
                        17,
                        0
                     ],
                     "setting":[
                        255,
                        0,
                        0,
                        0
                     ]
                  },
                  {
                     "start_time":[
                        17,
                        1
                     ],
                     "setting":[
                        0,
                        255,
                        0,
                        0
                     ]
                  },
                  {
                     "start_time":[
                        17,
                        2
                     ],
                     "setting":[
                        255,
                        255,
                        0,
                        0
                     ]
                  },
                  {
                     "start_time":[
                        17,
                        3
                     ],
                     "setting":[
                        255,
                        255,
                        255,
                        0
                     ]
                  },
                  {
                     "start_time":[
                        17,
                        4
                     ],
                     "setting":[
                        0,
                        255,
                        255,
                        255
                     ]
                  },
                  {
                     "start_time":[
                        17,
                        5
                     ],
                     "setting":[
                        0,
                        0,
                        255,
                        255
                     ]
                  },
                  {
                     "start_time":[
                        17,
                        6
                     ],
                     "setting":[
                        50,
                        120,
                        150,
                        200
                     ]
                  },
                  {
                     "start_time":[
                        17,
                        7
                     ],
                     "setting":[
                        0,
                        150,
                        150,
                        0
                     ]
                  },
                  {
                     "start_time":[
                        17,
                        8
                     ],
                     "setting":[
                        0,
                        0,
                        0,
                        0
                     ]
                  },
                  {
                     "start_time":[
                        17,
                        9
                     ],
                     "setting":[
                        255,
                        0,
                        0,
                        0
                     ]
                  },
                  {
                     "start_time":[
                        17,
                        10
                     ],
                     "setting":[
                        255,
                        0,
                        0,
                        0
                     ]
                  },
                  {
                     "start_time":[
                        17,
                        11
                     ],
                     "setting":[
                        0,
                        255,
                        0,
                        0
                     ]
                  },
                  {
                     "start_time":[
                        17,
                        12
                     ],
                     "setting":[
                        255,
                        255,
                        0,
                        0
                     ]
                  },
                  {
                     "start_time":[
                        17,
                        13
                     ],
                     "setting":[
                        255,
                        255,
                        255,
                        0
                     ]
                  },
                  {
                     "start_time":[
                        17,
                        14
                     ],
                     "setting":[
                        0,
                        255,
                        255,
                        255
                     ]
                  },
                  {
                     "start_time":[
                        17,
                        15
                     ],
                     "setting":[
                        0,
                        0,
                        255,
                        255
                     ]
                  },
                  {
                     "start_time":[
                        17,
                        16
                     ],
                     "setting":[
                        0,
                        0,
                        0,
                        255
                     ]
                  },
                  {
                     "start_time":[
                        17,
                        17
                     ],
                     "setting":[
                        50,
                        120,
                        150,
                        200
                     ]
                  },
                  {
                     "start_time":[
                        17,
                        19
                     ],
                     "setting":[
                        0,
                        150,
                        150,
                        0
                     ]
                  },
                  {
                     "start_time":[
                        17,
                        20
                     ],
                     "setting":[
                        0,
                        0,
                        0,
                        0
                     ]
                  },
                  {
                     "start_time":[
                        17,
                        21
                     ],
                     "setting":[
                        0,
                        255,
                        0,
                        0
                     ]
                  },
                  {
                     "start_time":[
                        17,
                        22
                     ],
                     "setting":[
                        255,
                        255,
                        0,
                        0
                     ]
                  },
                  {
                     "start_time":[
                        17,
                        23
                     ],
                     "setting":[
                        255,
                        255,
                        255,
                        0
                     ]
                  },
                  {
                     "start_time":[
                        17,
                        24
                     ],
                     "setting":[
                        0,
                        255,
                        255,
                        255
                     ]
                  },
                  {
                     "start_time":[
                        17,
                        25
                     ],
                     "setting":[
                        0,
                        0,
                        255,
                        255
                     ]
                  },
                  {
                     "start_time":[
                        17,
                        26
                     ],
                     "setting":[
                        0,
                        0,
                        0,
                        255
                     ]
                  },
                  {
                     "start_time":[
                        17,
                        27
                     ],
                     "setting":[
                        50,
                        120,
                        150,
                        200
                     ]
                  },
                  {
                     "start_time":[
                        17,
                        28
                     ],
                     "setting":[
                        0,
                        150,
                        150,
                        0
                     ]
                  },
                  {
                     "start_time":[
                        17,
                        29
                     ],
                     "setting":[
                        0,
                        0,
                        0,
                        0
                     ]
                  },
                  {
                     "start_time":[
                        17,
                        30
                     ],
                     "setting":[
                        255,
                        0,
                        0,
                        0
                     ]
                  },
                  {
                     "start_time":[
                        17,
                        31
                     ],
                     "setting":[
                        0,
                        255,
                        0,
                        0
                     ]
                  },
                  {
                     "start_time":[
                        17,
                        32
                     ],
                     "setting":[
                        255,
                        255,
                        0,
                        0
                     ]
                  },
                  {
                     "start_time":[
                        17,
                        33
                     ],
                     "setting":[
                        255,
                        255,
                        255,
                        0
                     ]
                  },
                  {
                     "start_time":[
                        17,
                        34
                     ],
                     "setting":[
                        0,
                        255,
                        255,
                        255
                     ]
                  },
                  {
                     "start_time":[
                        17,
                        35
                     ],
                     "setting":[
                        0,
                        0,
                        255,
                        255
                     ]
                  },
                  {
                     "start_time":[
                        17,
                        36
                     ],
                     "setting":[
                        0,
                        0,
                        0,
                        255
                     ]
                  },
                  {
                     "start_time":[
                        17,
                        37
                     ],
                     "setting":[
                        50,
                        120,
                        150,
                        200
                     ]
                  },
                  {
                     "start_time":[
                        17,
                        38
                     ],
                     "setting":[
                        0,
                        150,
                        150,
                        0
                     ]
                  },
                  {
                     "start_time":[
                        17,
                        39
                     ],
                     "setting":[
                        0,
                        0,
                        0,
                        0
                     ]
                  },
                  {
                     "start_time":[
                        17,
                        40
                     ],
                     "setting":[
                        255,
                        0,
                        0,
                        0
                     ]
                  },
                  {
                     "start_time":[
                        17,
                        41
                     ],
                     "setting":[
                        0,
                        255,
                        0,
                        0
                     ]
                  },
                  {
                     "start_time":[
                        17,
                        42
                     ],
                     "setting":[
                        255,
                        255,
                        0,
                        0
                     ]
                  },
                  {
                     "start_time":[
                        17,
                        43
                     ],
                     "setting":[
                        255,
                        255,
                        255,
                        0
                     ]
                  },
                  {
                     "start_time":[
                        17,
                        44
                     ],
                     "setting":[
                        0,
                        255,
                        255,
                        255
                     ]
                  },
                  {
                     "start_time":[
                        17,
                        45
                     ],
                     "setting":[
                        0,
                        0,
                        255,
                        255
                     ]
                  },
                  {
                     "start_time":[
                        17,
                        46
                     ],
                     "setting":[
                        0,
                        0,
                        0,
                        255
                     ]
                  },
                  {
                     "start_time":[
                        17,
                        47
                     ],
                     "setting":[
                        50,
                        120,
                        150,
                        200
                     ]
                  },
                  {
                     "start_time":[
                        17,
                        48
                     ],
                     "setting":[
                        0,
                        150,
                        150,
                        0
                     ]
                  },
                  {
                     "start_time":[
                        17,
                        49
                     ],
                     "setting":[
                        0,
                        0,
                        0,
                        0
                     ]
                  },
                  {
                     "start_time":[
                        17,
                        50
                     ],
                     "setting":[
                        255,
                        0,
                        0,
                        0
                     ]
                  },
                  {
                     "start_time":[
                        17,
                        51
                     ],
                     "setting":[
                        0,
                        255,
                        0,
                        0
                     ]
                  },
                  {
                     "start_time":[
                        17,
                        52
                     ],
                     "setting":[
                        255,
                        255,
                        0,
                        0
                     ]
                  },
                  {
                     "start_time":[
                        17,
                        53
                     ],
                     "setting":[
                        255,
                        255,
                        255,
                        0
                     ]
                  },
                  {
                     "start_time":[
                        17,
                        54
                     ],
                     "setting":[
                        0,
                        255,
                        255,
                        255
                     ]
                  },
                  {
                     "start_time":[
                        17,
                        55
                     ],
                     "setting":[
                        0,
                        0,
                        255,
                        255
                     ]
                  },
                  {
                     "start_time":[
                        17,
                        56
                     ],
                     "setting":[
                        0,
                        0,
                        0,
                        255
                     ]
                  },
                  {
                     "start_time":[
                        17,
                        57
                     ],
                     "setting":[
                        50,
                        120,
                        150,
                        200
                     ]
                  },
                  {
                     "start_time":[
                        17,
                        58
                     ],
                     "setting":[
                        0,
                        150,
                        150,
                        0
                     ]
                  },
                  {
                     "start_time":[
                        17,
                        59
                     ],
                     "setting":[
                        0,
                        0,
                        0,
                        0
                     ]
                  },
                  {
                     "start_time":[
                        18,
                        0
                     ],
                     "setting":[
                        255
                        255,
                        255,
                        255
                     ]
                  }
               ]
            }
         ]
      },
   ],
   "recipe_id":"6176e6e1c12a7e4a97ef7136",
   "trial_name":"test_trial_03.02.2022",
   "device_id":"60f1a223786cb0a4a6a5a175",
   "device_name":"Tyler_test_device_08022021",
   "start_date":1746241768.229
}
