trial = {
   "_id":"621fa7e8ac211300166be205",
   "model_name":"TemplateRecipe",
   "recipe_name":"FFA_Test_Recipe_V1",
   "recipe_variable":"Light and Temperature",
   "phases":[
      {
         "name":"growth",
         "phase_start":0,
         "step":[
            {
               "circulation_fan":[
                  {
                     "start_time":[
                        0,
                        0
                     ],
                     "setting":1
                  }
               ]
            },
            {
               "temperature":[
                  {
                     "start_time":[
                        0,
                        0
                     ],
                     "setting":90
                  }
               ]
            },
	    {
               "pump_amount":[
                  {
                     "start_time":[
                        11,
                        7
                     ],
                     "setting":20
                  },
		  {
                     "start_time":[
                        12,
                        8
                     ],
                     "setting":30
                  },
		  {
                     "start_time":[
                        12,
                        15
                     ],
                     "setting":30
                  }
               ]
            },
            {
               "light_intensity":[
                  {
                     "start_time":[
                        0,
                        0
                     ],
                     "setting":[
                        0,
                        0,
                        0,
                        0
                     ]
                  },
                  {
                     "start_time":[
                        9,
                        0
                     ],
                     "setting":[
                        100,
                        100,
                        100,
                        100
                     ]
                  },
                  {
                     "start_time":[
                        12,
                        30
                     ],
                     "setting":[
                        0,
                        0,
                        0,
                        0
                     ]
                  },
                  {
                     "start_time":[
                        12,
                        45
                     ],
                     "setting":[
                        125,
                        200,
                        200,
                        100
                     ]
                  },
                  {
                     "start_time":[
                        12,
                        55
                     ],
                     "setting":[
                        0,
                        0,
                        0,
                        0
                     ]
                  },
                  {
                     "start_time":[
                        13,
                        0
                     ],
                     "setting":[
                        125,
                        200,
                        200,
                        100
                     ]
                  },
                  {
                     "start_time":[
                        14,
                        15
                     ],
                     "setting":[
                        0,
                        0,
                        0,
                        0
                     ]
                  },
                  {
                     "start_time":[
                        14,
                        20
                     ],
                     "setting":[
                        125,
                        200,
                        200,
                        100
                     ]
                  },
                  {
                     "start_time":[
                        17,
                        0
                     ],
                     "setting":[
                        0,
                        0,
                        0,
                        0
                     ]
                  }
               ]
            }
         ]
      },
      {
         "name":"veg",
         "phase_start":28,
         "step":[
            {
               "circulation_fan":[
                  {
                     "start_time":[
                        0,
                        0
                     ],
                     "setting":1
                  }
               ]
            },
            {
               "temperature":[
                  {
                     "start_time":[
                        0,
                        0
                     ],
                     "setting":75
                  },
                  {
                     "start_time":[
                        16,
                        0
                     ],
                     "setting":85
                  }
               ]
            },
	    {
               "pump_amount":[
                  {
                     "start_time":[
                        11,
                        10
                     ],
                     "setting":20
                  }
               ]
            },
            {
               "light_intensity":[
                  {
                     "start_time":[
                        0,
                        0
                     ],
                     "setting":[
                        0,
                        0,
                        0,
                        0
                     ]
                  },
                  {
                     "start_time":[
                        10,
                        0
                     ],
                     "setting":[
                        75,
                        75,
                        75,
                        75
                     ]
                  }
               ]
            }
         ]
      }
   ],
   "recipe_id":"6176e6e1c12a7e4a97ef7136",
   "trial_name":"test_trial_03.02.2022",
   "device_id":"60f1a223786cb0a4a6a5a175",
   "device_name":"Tyler_test_device_08022021",
   "start_date":1646241768.229
}
